# roles/create-develop-pipeline/defaults/main.yml
application_name: dev-tasklist
build_ns: tasklist-build
dev_ns: tasklist-dev
pipeline_branch: develop
development_branch: develop
context_dir: openshift/jenkins
development_pipeline_file: development-pipeline.groovy
build_timeout: '10'
deployment_timeout: '10'
app_domain: ''
target_is_name: dev-tasklist
