apiVersion: v1
kind: Template
labels:
  template: secret-trigger-template
metadata:
  annotations:
    description: Template for creating a secret for a webhook trigger.
  name: secret-trigger-template
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: ${NAME}
    labels:
      app: ${APP_NAME}
      pipeline: ${REVISION}
    annotations:
      openshift.io/generated-by: secret-trigger-template
  data:
    WebHookSecretKey: ${SECRET_VALUE}
parameters:
- name: NAME
  description: Name of secret
  required: true
- name: SECRET_VALUE
  generate: expression
  from: "[A-Za-z0-9]{20}"
  required: true
- name: REVISION
  description: Application revision. Can be development (default) or release
  value: development
- name: APP_NAME
  description: Name of application this secret is related to.
  required: true
message: Created a secret for a webhook trigger. Trigger value is ${SECRET_VALUE}
