smtp.host=
smtp.port=
smtp.from=
smtp.username=
smtp.password=
server.port=8090

security.oauth2.enabled=true
spring.security.oauth2.client.provider.keycloak.issuer-uri=<keycloak-realm-uri>
spring.security.oauth2.client.registration.keycloak.client-id=<client-id>
spring.security.oauth2.client.registration.keycloak.client-secret=<client-secret>
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.resourceserver.jwt.issuer-uri: <keycloak-realm-uri>
