# roles/openshift-login/tasks/main.yml
---
- name: Check if logged in
  command: "oc whoami"
  register: logged_check_result
  ignore_errors: true
  no_log: true

- name: Check openshift login url
  fail:
    msg: "Openshift login url is not defined!"
  when: login_url is not defined

- name: Openshift login with configured username and password
  command: "oc login {{ login_url }} -u {{ openshift_username }} -p {{ openshift_password }} --insecure-skip-tls-verify"
  no_log: false
  when: logged_check_result.rc == 1 and ( openshift_password is defined and openshift_username | length > 0 )

- name: Prompt openshift username
  pause:
    prompt: What is your openshift username?
  register: username_input
  when: logged_check_result.rc == 1 and openshift_username is not defined

- name: Prompt openshift password
  pause:
    prompt: What is your openshift password?
    echo: no
  register: password_input
  when: logged_check_result.rc == 1 and ( openshift_password is not defined or openshift_password | length == 0 )

- name: Openshift login with user input username and password
  command: "oc login {{ login_url }} -u {{ username_input.user_input }} -p {{ password_input.user_input }} --insecure-skip-tls-verify"
  no_log: true
  when: logged_check_result.rc == 1 and openshift_username is not defined and openshift_password is not defined

- name: Openshift login with user input password and configured username
  command: "oc login {{ login_url }} -u {{ openshift_username }} -p {{ password_input.user_input }} --insecure-skip-tls-verify"
  no_log: true
  when: logged_check_result.rc == 1 and openshift_username is defined and openshift_password is not defined
