apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: binary-s2i-template
  creationTimestamp: null
  labels:
    app: dev-tasklist
    pipeline: development
    template: binary-s2i-template
  name: dev-tasklist-s2i-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: dev-tasklist-s2i-build:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11-rhel8:1.3
      pullSecret:
        name: "tasklist-image-pull"
    type: Source
  triggers: []
