apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: dev-tasklist
    pipeline: development
  name: dev-tasklist
#  resourceVersion: '1'
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: dev-tasklist
    deploymentconfig: dev-tasklist
    pipeline: development
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: dev-tasklist
        deploymentconfig: dev-tasklist
        pipeline: development
    spec:
      containers:
        - env:
            - name: DB_URL
              value: jdbc:sqlite:/data/tasklist.db
            - name: OPENSHIFT_ENV_VAR
              value: DEV
            - name: CONFIG_FILE
              value: /config/tasklist.properties
          image: >-
            image-registry.openshift-image-registry.svc:5000/tasklist-dev/dev-tasklist-s2i-build:latest
          imagePullPolicy: Always
#          livenessProbe:
#            failureThreshold: 3
#            httpGet:
#              path: /health
#              port: 9100
#              scheme: HTTP
#            initialDelaySeconds: 40
#            periodSeconds: 10
#            successThreshold: 1
#            timeoutSeconds: 1
          name: dev-tasklist
          ports:
            - containerPort: 8778
              protocol: TCP
              name: jolokia
            - containerPort: 8080
              protocol: TCP
              name: app
            - containerPort: 9100
              protocol: TCP
              name: management
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /tasklist/api/v1/hello/readinessProbe
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data-volume
            - mountPath: /config
              name: configuration-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: dev-tasklist-data
        - name: configuration-volume
          configMap:
            name: dev-tasklist-config
            defaultMode: 420
  test: false
  triggers: []