apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: dev-tasklist
    pipeline: release
    template: binary-s2i-template
  name: dev-tasklist-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
