# roles/setup-namespace/tasks/main.yml
---
- name: Namespace exists
  include_role:
    name: create-namespace
  vars:
    namespace: "{{ namespace }}"

- name: Give Jenkins edit access to namespace
  include_role:
    name: set-user-role-for-namespace
  vars:
    role: edit
    user: "system:serviceaccount:{{ jenkins_namespace }}:jenkins"
    target_namespace: "{{ namespace }}"
