# roles/setup-namespace/tasks/main.yml
---
- name: Namespace exists
  include_role:
    name: create-namespace
  vars:
    namespace: "{{ namespace_name }}"

- name: Give Jenkins edit access to namespace
  command: oc policy add-role-to-user edit system:serviceaccount:{{ jenkins_namespace }}:jenkins -n {{ namespace_name }}
  ignore_errors: true
