# roles/setup-namespace/tasks/main.yml
---
- name: Namespace exists
  include_role:
    name: create-namespace
  vars:
    namespace: "{{ namespace_name }}"

- name: Create rolebinding yaml file
  template:
    src: rb-jenkins-access.yaml.j2
    dest: /tmp/rb-jenkins-access.yaml

- name: Give Jenkins edit access to namespace
  shell: "oc apply -f /tmp/rb-jenkins-access.yaml --overwrite -n {{ namespace_name }}"
