---

- name: Install Tasklist
  hosts: tasklist
  gather_facts: no
  become: true

  tasks:
  - name: Create install directory
    file:
      path: "{{ install_dir }}"
      state: directory

  - name: Create bin directory into install directory
    file:
      path: "{{ install_dir }}/bin"
      state: directory

  - name: Create db directory into install directory
    file:
      path: "{{ install_dir }}/db"
      state: directory

  - name: Create conf directory into install directory
    file:
      path: "{{ install_dir }}/conf"
      state: directory

  - name: Create conf directory into install directory
    file:
      path: "{{ install_dir }}/log"
      state: directory

  - name: Copy jar
    include_role:
      name: copy_jar

  - name: Install and start service
    include_role:
      name: install_service
