---

- name: Uninstall Task List
  hosts: tasklist
  gather_facts: no
  become: true

  tasks:
  - name: Remove monit config
    file:
      path: /etc/monit.d/tasklist.rc
      state: absent
    when: setup_monit is defined and setup_monit

  - name: Restart monit
    systemd:
      name: monit
      state: restarted
    when: setup_monit is defined and setup_monit

  - name: Stop and disable service
    systemd:
      name: tasklist
      state: stopped
      enabled: no

  - name: Remove service
    file:
      path: /lib/systemd/system/tasklist.service
      state: absent

  - name: Refresh systemd
    systemd:
      daemon_reload: yes

  - name: Delete install directory
    file:
      path: "{{ install_dir }}"
      state: absent
