# roles/create-develop-pipeline/tasks/main.yml
---
- name: Setup generic webhook trigger secret with existing value for develop pipeline
  shell: "oc process --local -f {{ playbook_dir }}/files/secret-trigger-template.yaml -p NAME=dev-generic-trigger -p APP_NAME={{ application_name }} -p SECRET_VALUE={{ vault_generic_trigger_value }} "
  when: '"dev-generic-trigger" not in existing_build_project_secrets.stdout and vault_dev_generic_trigger_value is defined'

- name: Generate random value for generic webhook secret
  shell: "oc process --local -f {{ playbook_dir }}/files/secret-trigger-template.yaml -p NAME=dev-generic-trigger -p APP_NAME={{ application_name }} | awk \"NR==9{print $1}\" | sed -e \"s/^.*://g\" -e \"s/\\\"//g\" -e \"s/ //g\""
  register: dev_generic_trigger_value
  when: '"dev-generic-trigger" not in existing_build_project_secrets.stdout and vault_dev_generic_trigger_value is not defined'

- name: Setup generic webhook trigger secret with random value for develop pipeline
  shell: "oc create secret generic dev-generic-trigger --from-literal=WebHookSecretKey={{ dev_generic_trigger_value.stdout }} -n {{ build_ns }}"
  when: '"dev-generic-trigger" not in existing_build_project_secrets.stdout and vault_dev_generic_trigger_value is not defined'

- name: Setup Github webhook trigger secret with existing value for develop pipeline
  shell: "oc process --local -f {{ playbook_dir }}/files/secret-trigger-template.yaml -p NAME=dev-github-trigger -p APP_NAME={{ application_name }} -p SECRET_VALUE={{ vault_github_trigger_value }} "
  when: '"dev-github-trigger" not in existing_build_project_secrets.stdout and vault_dev_github_trigger_value is defined'

- name: Generate random value for Github webhook secret
  shell: "oc process --local -f {{ playbook_dir }}/files/secret-trigger-template.yaml -p NAME=dev-github-trigger -p APP_NAME={{ application_name }} | awk \"NR==9{print $1}\" | sed -e \"s/^.*://g\" -e \"s/\\\"//g\" -e \"s/ //g\""
  register: dev_github_trigger_value
  when: '"dev-github-trigger" not in existing_build_project_secrets.stdout and vault_dev_github_trigger_value is not defined'

- name: Setup Github webhook trigger secret with random value for develop pipeline
  shell: "oc create secret generic dev-github-trigger --from-literal=WebHookSecretKey={{ dev_github_trigger_value.stdout }} -n {{ build_ns }}"
  when: '"dev-github-trigger" not in existing_build_project_secrets.stdout and vault_dev_github_trigger_value is not defined'

- name: Setup development pipeline
  shell: "oc process --local -f {{ playbook_dir }}/files/development-pipeline-bc-template.yaml -p APP_NAME={{ application_name }} -p GIT_URL={{ git_url }} -p GIT_CREDENTIALS_ID={{ build_ns }}-tasklist-git-clone-secret -p GIT_BRANCH={{ development_branch }} -p PIPELINE_GIT_BRANCH={{ pipeline_branch }} -p CONTEXT_DIR={{ context_dir }} -p JENKINS_FILENAME={{ development_pipeline_file }} -p BUILD_TIMEOUT={{ build_timeout }} -p DEPLOYMENT_TIMEOUT={{ deployment_timeout }} -p BUILD_NAMESPACE={{ build_ns }} -p DEV_NAMESPACE={{ dev_ns }} -p APP_DOMAIN={{ app_domain }} -p TARGET_IMAGESTREAM_NAME={{ target_is_name }} | oc apply -f - -n {{ build_ns }}"

- name: Get github trigger secret value
  shell: "oc get secret dev-github-trigger -o yaml -n tasklist-build | grep WebHookSecretKey | awk '{ print $2 }' | base64 -d"
  register: develop_github_trigger_secret_value

- name: Get github trigger secret url
  shell: "oc describe bc tasklist-development-pipeline -n {{ build_ns }} | grep -A 1 'Webhook GitHub' | awk '{ if(NR==2) print $2 }' | sed 's/<secret>/{{ develop_github_trigger_secret_value.stdout }}/'"
  register: develop_github_trigger_url

- name: Get generic trigger secret value
  shell: "oc get secret dev-generic-trigger -o yaml -n tasklist-build | grep WebHookSecretKey | awk '{ print $2 }' | base64 -d"
  register: develop_generic_trigger_secret_value

- name: Get generic trigger secret url
  shell: "oc describe bc tasklist-development-pipeline -n {{ build_ns }} | grep -A 1 'Webhook Generic' | awk '{ if(NR==2) print $2 }' | sed 's/<secret>/{{ develop_generic_trigger_secret_value.stdout }}/'"
  register: develop_generic_trigger_url
